# Generated by Django 4.0.8 on 2023-08-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=200, null=True)),
                ('group', models.CharField(choices=[('0', 'Physical Customers'), ('1', 'Online Customers'), ('2', 'Hybrid Customers')], default=0, max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('0', 'Cash'), ('1', 'Mpesa'), ('2', 'Bank'), ('3', 'Other')], default='Cash', max_length=50)),
                ('payment_total', models.CharField(max_length=60)),
                ('payment_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=60, null=True)),
                ('cost', models.FloatField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('tax', models.CharField(choices=[('16', 'VAT(16%)'), ('0', 'NO TAX')], default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_ref', models.AutoField(primary_key=True, serialize=False)),
                ('sale_total', models.FloatField()),
                ('sale_tax', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.customer')),
                ('products', models.ManyToManyField(to='user_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField()),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.product')),
                ('sale_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.sale')),
            ],
        ),
    ]
