# Generated by Django 4.2.2 on 2023-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('group', models.CharField(choices=[('0', 'Physical Customers'), ('1', 'Online Customers'), ('2', 'Hybrid Customers')], default=0, max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_total', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('16', 'VAT(16%)'), ('0', 'ZERO-RATED'), ('0', 'EXEMPTED')], default=0, max_length=20),
        ),
    ]
