# Generated by Django 4.2.2 on 2023-06-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('16', 'VAT(16%)'), ('0', 'ZERO-RATED'), ('0', 'EXEMPTED')], default=0, max_length=20),
        ),
    ]
