# Generated by Django 4.2.2 on 2023-06-16 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_product_barcode_product_cost_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('group', models.CharField(choices=[('0', 'Physical Customers'), ('1', 'Online Customers'), ('2', 'Hybrid Customers')], default=0, max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 17, 27, 59, 354365))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 17, 28, 17, 200746), verbose_name=datetime.datetime(2023, 6, 16, 17, 27, 59, 353367)),
            preserve_default=False,
        ),
    ]
