# Generated by Django 4.2.2 on 2023-06-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_customer_sale_product_barcode_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.product'),
        ),
    ]
