# Generated by Django 4.2.2 on 2023-06-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_customer_date_added_remove_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default='Date Added', verbose_name=datetime.datetime(2023, 6, 16, 17, 32, 33, 573513)),
            preserve_default=False,
        ),
    ]
