# Generated by Django 4.2.2 on 2023-06-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
    ]
