# Generated by Django 4.2.2 on 2023-06-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 17, 34, 30, 41744)),
        ),
    ]
