# Generated by Django 4.2.2 on 2023-06-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_remove_sale_product_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='products',
        ),
    ]
